### ISSUE TITLE
Fatal Error after a while of usage

### ISSUE THREAD

**Issue by a-haan** [taylorbryant/jekyll-starter-tailwind#135]
Hi,

I'm enjoying your repo, I've come across the same fatal error after using the development process - after awhile of changing code and saving changes, the script crashes out - I've tested this on Windows and Mac OSX with the same results - the error below is output upon crashing.

**<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1009ce8d9]
Security context: 0x10eebe6808d1 <JSObject>
    1: handle(aka handle) [0x10ee39e76f09] [/Users/ahaan/Documents/GitHub/CC-a-haan-jekyll-SRC-Tailwind/node_modules/tailwindcss/lib/lib/substituteClassApplyAtRules.js:~123] [pc=0x741ccdf2719](this=0x10eec2b401b9 <null>,0x10ee39e76f49 <JSFunction (sfi = 0x10eeacb9e5a9)>,0x10ee884eeb71 <Node map = 0x10eee55a0e69>)
    2: /* anonymous */(aka /* anonymous */) [0x1...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1011bdf85 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10009d569 node::Abort() [/usr/local/bin/node]
 3: 0x10009d6cf node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 4: 0x1001de957 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1001de8f7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 6: 0x100364635 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 7: 0x100365e8a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 8: 0x10036290e v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1003606c0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
10: 0x10036c4ea v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
11: 0x10036c571 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
12: 0x10033a78a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
13: 0x100689cc0 v8::internal::Runtime_AllocateInOldGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
14: 0x1009ce8d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jekyll-starter-tailwind@6.0.0 dev: `cross-env NODE_ENV=development gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jekyll-starter-tailwind@6.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahaan/.npm/_logs/2021-02-14T18_20_41_950Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jekyll-starter-tailwind@6.0.0 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jekyll-starter-tailwind@6.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahaan/.npm/_logs/2021-02-14T18_20_42_027Z-debug.log**

Below is whats found in the debug log

**0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle jekyll-starter-tailwind@6.0.0~predev: jekyll-starter-tailwind@6.0.0
6 info lifecycle jekyll-starter-tailwind@6.0.0~dev: jekyll-starter-tailwind@6.0.0
7 verbose lifecycle jekyll-starter-tailwind@6.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle jekyll-starter-tailwind@6.0.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ahaan/Documents/GitHub/CC-a-haan-jekyll-SRC-Tailwind/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ahaan/Documents/GitHub/CC-a-haan-jekyll-SRC-Tailwind/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle jekyll-starter-tailwind@6.0.0~dev: CWD: /Users/ahaan/Documents/GitHub/CC-a-haan-jekyll-SRC-Tailwind
10 silly lifecycle jekyll-starter-tailwind@6.0.0~dev: Args: [ '-c', 'cross-env NODE_ENV=development gulp serve' ]
11 silly lifecycle jekyll-starter-tailwind@6.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle jekyll-starter-tailwind@6.0.0~dev: Failed to exec dev script
13 verbose stack Error: jekyll-starter-tailwind@6.0.0 dev: `cross-env NODE_ENV=development gulp serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid jekyll-starter-tailwind@6.0.0
15 verbose cwd /Users/ahaan/Documents/GitHub/CC-a-haan-jekyll-SRC-Tailwind
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error jekyll-starter-tailwind@6.0.0 dev: `cross-env NODE_ENV=development gulp serve`
22 error Exit status 1
23 error Failed at the jekyll-starter-tailwind@6.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
**

**Comment by lincoln-chawora** [comment]
I'm also getting this, @a-haan. I'll have a look at it tomorrow if I've got some time, from a quick read of your message looks like a memory issue. So I'm thinking maybe the constant rebuilds of the site take up a lot of memory (which explains why my laptop fans have randomly been starting), I'll try and workout if there's a way to increase the memory in npm if i can't make the builds more efficient. This kinda thing also happens sometimes when using composer so hopefully a fix for this won't be too hard to find

**Comment by a-haan** [comment]
@lincoln-chawora thank you

**Comment by keikhcheung** [comment]
Getting the same error. 😕 
Any luck @a-haan @lincoln-chawora that you found a solution?
